security:
  oauth2:
    resource:
      userInfoUri: http://192.168.1.21:8901/auth/user

#Setting the logging levels for the service
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    cc.coopersoft: DEBUG


eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://192.168.1.21:8761/eureka/

spring:
  cloud:
    stream:
      bindings:
        certificateExecute:
          destination: certificateChangeTopic
          content-type: application/json
      kafka:
        binder:
          brokers: 192.168.1.21

signing:
  key: "345345fsdfsf5345"


business:
  readyLimitDay: 10